//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.18 at 10:23:52 PM EST 
//


package com.minosiants.eclipse.maven.model.classpath;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}attributes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="path" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="/tv.quotiny.core"/>
 *             &lt;enumeration value="/tv.quotiny.facebook"/>
 *             &lt;enumeration value="/tv.quotiny.rest.api"/>
 *             &lt;enumeration value="/tv.quotiny.twitter"/>
 *             &lt;enumeration value="/tv.quotiny.vimeo"/>
 *             &lt;enumeration value="/tv.quotiny.web.common"/>
 *             &lt;enumeration value="/tv.quotiny.youtube"/>
 *             &lt;enumeration value="org.eclipse.jdt.launching.JRE_CONTAINER"/>
 *             &lt;enumeration value="org.eclipse.jst.j2ee.internal.module.container"/>
 *             &lt;enumeration value="org.eclipse.jst.j2ee.internal.web.container"/>
 *             &lt;enumeration value="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER"/>
 *             &lt;enumeration value="org.scala-ide.sdt.launching.SCALA_CONTAINER"/>
 *             &lt;enumeration value="src/main/resources"/>
 *             &lt;enumeration value="src/main/scala"/>
 *             &lt;enumeration value="src/test/scala"/>
 *             &lt;enumeration value="target/classes"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="output">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="target/classes"/>
 *             &lt;enumeration value="target/test-classes"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="kind" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="con"/>
 *             &lt;enumeration value="output"/>
 *             &lt;enumeration value="src"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="excluding">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="**"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="combineaccessrules" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attributes"
})
@XmlRootElement(name = "classpathentry")
public class Classpathentry {

    protected Attributes attributes;
    @XmlAttribute(required = true)
    protected String path;
    @XmlAttribute
    protected String output;
    @XmlAttribute(required = true)
    protected String kind;
    @XmlAttribute
    protected String excluding;
    @XmlAttribute
    protected Boolean combineaccessrules;

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link Attributes }
     *     
     */
    public Attributes getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attributes }
     *     
     */
    public Classpathentry setAttributes(Attributes value) {
        this.attributes = value;
        return this;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public Classpathentry setPath(String value) {
        this.path = value;
        return this;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public Classpathentry setOutput(String value) {
        this.output = value;
        return this;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public Classpathentry setKind(String value) {
        this.kind = value;
        return this;
    }

    /**
     * Gets the value of the excluding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcluding() {
        return excluding;
    }

    /**
     * Sets the value of the excluding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public Classpathentry setExcluding(String value) {
        this.excluding = value;
        return this;
    }

    /**
     * Gets the value of the combineaccessrules property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCombineaccessrules() {
        return combineaccessrules;
    }

    /**
     * Sets the value of the combineaccessrules property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public Classpathentry setCombineaccessrules(Boolean value) {
        this.combineaccessrules = value;
        return this;
    }

}
